# Generated by Django 5.0.3 on 2024-03-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_record_uni_slug_alter_record_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
